### ISSUE TITLE
css 在横线中间加入文字

### ISSUE THREAD

**Issue by qq2441570482** [qq2441570482/gist#1]

**Comment by qq2441570482** [comment]
```html
<div class="container">
  <div class="line">
    <span class="text">or</span>
  </div>
</div>
```

相关的css代码：

```css
.container {
  width: 800px;
  margin: 0 auto;
  height: 600px;
  background-color: white;
  border: 1px solid transparent;
}

.line {
  height: 20px;
  width: 300px;
  margin: 0 auto 20px;
  border-bottom: 1px solid red;
  text-align: center;
  background-color: inherit;
}

.text {
  line-height: 40px;
  text-transform: uppercase;
  background-color: inherit;
  padding: 0 10px;
}

```

可以看到，需要解决的问题就是：对于文字div需要用background-color直接覆盖父级div的背景颜色即可。

**Comment by aaronzjc** [comment]
我也遇到这么个需求，我是这么实现的
```css
.line {
    width: 100%;
    text-align: center;
    height: 1px;
    background: #ccc;
}
.text {
    display: inline-block;
    height: 20px;
    transform: translateY(-10px);
    background: #fff;
    padding: 0px 10px;
}
```
